In [1]:
# Import libraries
import pandas as pd
from pandas import DataFrame
import numpy as np
#pd.set_option('display.max_columns', None)  
import seaborn as sns

In [4]:
#Import data for model building and prediction
model_data=pd.read_csv('data/final_model_data')

In [5]:
model_data.head(2)

drug_1         drug_2  Diarrhoea  Dyspnoea  Nausea  Pneumonia  Pyrexia  \
0  acarbose     acebutolol          0         1       0          0        1   
1  acarbose  acenocoumarol          1         1       0          0        1   

   Vomiting  0_sub  1_sub  ...  871_sub  872_sub  873_sub  874_sub  875_sub  \
0         0      1      1  ...        0        0        0        0        0   
1         1      1      1  ...        0        0        0        0        0   

   876_sub  877_sub  878_sub  879_sub  880_sub  
0        0        0        0        0        0  
1        0        0        0        0        0  

[2 rows x 889 columns]

In [ ]:
model_data

In [ ]:
#hamming distance- to assess how good predictions are, on an average. - for multiclass 
#

In [8]:
model_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123069 entries, 0 to 123068
Columns: 889 entries, drug_1 to 880_sub
dtypes: int64(887), object(2)
memory usage: 834.7+ MB


In [31]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

## Prediction for Diarrhoea

In [23]:
X=model_data.iloc[:,8:]
y=model_data.iloc[:, 2]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, random_state = 321)

In [26]:
from sklearn.linear_model import LogisticRegression

In [39]:
clf = LogisticRegression(class_weight='balanced')

In [40]:
clf.fit(X_train, y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [41]:
probas = clf.predict_proba(X_train)
preds = clf.predict(X_train)

In [42]:
print(X_train.head(1))
print(probas[0])
print(preds[0])

        0_sub  1_sub  2_sub  3_sub  4_sub  5_sub  6_sub  7_sub  8_sub  9_sub  \
113382      1      1      1      1      0      0      0      0      0      1   

        ...  871_sub  872_sub  873_sub  874_sub  875_sub  876_sub  877_sub  \
113382  ...        0        0        0        0        0        0        0   

        878_sub  879_sub  880_sub  
113382        0        0        0  

[1 rows x 881 columns]
[0.4247588 0.5752412]
1


In [43]:
y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)

In [44]:
print(y_pred_proba[0])

[0.53119937 0.46880063]


In [45]:
accuracy_score(y_test, y_pred)

0.6029641185647426

In [46]:
print(confusion_matrix(y_test, y_pred))

[[ 3533  3204]
 [ 9012 15019]]


### Predicting Dyspnoea (difficulty breathing)

In [47]:
X1=model_data.iloc[:,8:]
y1=model_data.iloc[:,3]

In [48]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, stratify = y1, random_state = 321)

In [49]:
clf1 = LogisticRegression(class_weight="balanced")

In [50]:
clf1.fit(X1_train, y1_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
probas1 = clf1.predict_proba(X1_train)
preds1 = clf1.predict(X1_train)

In [68]:
print(X1_train.head(1))
print(probas1[0])
print(preds1[0])

       0_sub  1_sub  2_sub  3_sub  4_sub  5_sub  6_sub  7_sub  8_sub  9_sub  \
55333      1      1      1      0      0      0      0      0      0      1   

       ...  871_sub  872_sub  873_sub  874_sub  875_sub  876_sub  877_sub  \
55333  ...        0        0        0        0        0        0        0   

       878_sub  879_sub  880_sub  
55333        0        0        0  

[1 rows x 881 columns]
[0.40809632 0.59190368]
1


In [69]:
y1_pred1 = clf.predict(X1_test)
y1_pred_proba1 = clf.predict_proba(X1_test)

In [70]:
print(y1_pred_proba1[0])

[0.42827186 0.57172814]


In [71]:
accuracy_score(y1_test, y1_pred1)

0.5905161206448258

In [72]:
print(confusion_matrix(y1_test, y1_pred1))

[[ 3000  3082]
 [ 9517 15169]]


### Predicting Nausea (difficulty breathing)

In [86]:
X3=model_data.iloc[:,8:]
y3=model_data.iloc[:,4]

In [87]:
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, stratify = y3, random_state = 321)

In [88]:
clf3 = LogisticRegression(class_weight='balanced')

In [89]:
clf3.fit(X3_train, y3_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [90]:
probas3 = clf3.predict_proba(X3_train)
preds3 = clf3.predict(X3_train)

In [91]:
print(X3_train.head(1))
print(probas3[0])
print(preds3[0])

        0_sub  1_sub  2_sub  3_sub  4_sub  5_sub  6_sub  7_sub  8_sub  9_sub  \
100022      1      1      1      1      0      0      0      0      0      1   

        ...  871_sub  872_sub  873_sub  874_sub  875_sub  876_sub  877_sub  \
100022  ...        0        0        0        0        0        0        0   

        878_sub  879_sub  880_sub  
100022        0        0        0  

[1 rows x 881 columns]
[0.38273193 0.61726807]
1


In [92]:
y_pred3 = clf.predict(X3_test)
y_pred_proba3 = clf.predict_proba(X3_test)

In [93]:
print(y_pred_proba3[0])

[0.44726178 0.55273822]


In [95]:
accuracy_score(y3_test, y_pred3)

0.593603744149766

In [ ]:
print(confusion_matrix(y3_test, y3_pred))

## Prediction for Pneumonia

In [73]:
X4=model_data.iloc[:,8:]
y4=model_data.iloc[:, 5]

In [74]:
X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, stratify = y4, random_state = 321)

In [75]:
from sklearn.linear_model import LogisticRegression

In [76]:
clf4 = LogisticRegression(class_weight='balanced')

In [77]:
clf4.fit(X4_train, y4_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [78]:
probas4 = clf4.predict_proba(X4_train)
preds4 = clf4.predict(X4_train)

In [79]:
print(X4_train.head(1))
print(probas4[0])
print(preds4[0])

       0_sub  1_sub  2_sub  3_sub  4_sub  5_sub  6_sub  7_sub  8_sub  9_sub  \
67107      1      1      1      0      0      0      0      0      0      1   

       ...  871_sub  872_sub  873_sub  874_sub  875_sub  876_sub  877_sub  \
67107  ...        0        0        0        0        0        0        0   

       878_sub  879_sub  880_sub  
67107        0        0        0  

[1 rows x 881 columns]
[0.4750138 0.5249862]
1


In [84]:
y_pred4 = clf4.predict(X4_test)
y_pred_proba4 = clf4.predict_proba(X4_test)

In [85]:
print(y_pred_proba4[0])

[0.52082338 0.47917662]


In [82]:
accuracy_score(y4_test, y_pred4)

0.5767680707228289

In [83]:
print(confusion_matrix(y4_test, y_pred4))

[[ 3862  4327]
 [ 8695 13884]]


## Prediction for Pyrexia (Fever)

In [96]:
X5=model_data.iloc[:,8:]
y5=model_data.iloc[:, 6]

In [97]:
X5_train, X5_test, y5_train, y5_test = train_test_split(X5, y5, stratify = y5, random_state = 321)

In [98]:
clf5 = LogisticRegression(class_weight='balanced')

In [99]:
clf5.fit(X5_train, y5_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [100]:
probas5 = clf5.predict_proba(X5_train)
preds5 = clf.predict(X5_train)

In [101]:
print(X5_train.head(1))
print(probas5[0])
print(preds5[0])

       0_sub  1_sub  2_sub  3_sub  4_sub  5_sub  6_sub  7_sub  8_sub  9_sub  \
52360      1      1      0      0      0      0      0      0      0      1   

       ...  871_sub  872_sub  873_sub  874_sub  875_sub  876_sub  877_sub  \
52360  ...        0        0        0        0        0        0        0   

       878_sub  879_sub  880_sub  
52360        0        0        0  

[1 rows x 881 columns]
[0.5017887 0.4982113]
1


In [102]:
y_pred5 = clf.predict(X5_test)
y_pred_proba5 = clf.predict_proba(X5_test)

In [103]:
print(y_pred_proba5[0])

[0.41432511 0.58567489]


In [104]:
accuracy_score(y5_test, y_pred5)

0.578198127925117

In [105]:
print(confusion_matrix(y5_test, y_pred5))

[[ 3720  4125]
 [ 8853 14070]]


## Prediction for Vomiting

In [106]:
X6=model_data.iloc[:,8:]
y6=model_data.iloc[:, 7]

In [107]:
X6_train, X6_test, y6_train, y6_test = train_test_split(X6, y6, stratify = y6, random_state = 321)

In [108]:
clf6 = LogisticRegression(class_weight='balanced')

In [109]:
clf6.fit(X6_train, y6_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [110]:
probas6 = clf6.predict_proba(X6_train)
preds6 = clf6.predict(X6_train)

In [111]:
print(X6_train.head(1))
print(probas6[0])
print(preds6[0])

      0_sub  1_sub  2_sub  3_sub  4_sub  5_sub  6_sub  7_sub  8_sub  9_sub  \
3385      1      1      1      0      0      0      0      0      0      1   

      ...  871_sub  872_sub  873_sub  874_sub  875_sub  876_sub  877_sub  \
3385  ...        0        0        0        0        0        0        0   

      878_sub  879_sub  880_sub  
3385        0        0        0  

[1 rows x 881 columns]
[0.43513251 0.56486749]
1


In [112]:
y_pred6 = clf6.predict(X6_test)
y_pred_proba6 = clf6.predict_proba(X6_test)

In [113]:
print(y_pred_proba6[0])

[0.44343061 0.55656939]


In [114]:
accuracy_score(y6_test, y_pred6)

0.578133125325013

In [115]:
print(confusion_matrix(y6_test, y_pred6))

[[ 3803  3219]
 [ 9761 13985]]


In [18]:
pip install scikit-multilearn

     |████████████████████████████████| 92kB 1.1MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [19]:
from skmultilearn.adapt import MLkNN

In [20]:
classifier = MLkNN(k=20)

In [22]:
from skmultilearn.problem_transform import BinaryRelevance